# Maintainer: Your Name <your.email@example.com>
pkgname=PromptFlow
pkgver=0.2.0
pkgrel=1
arch=('x86_64')
url="https://github.com/Shaharyar-developer/PromptFlow"
license=('MIT')
depends=('glibc')
makedepends=('rust' 'cargo' 'git')
source=("git+https://github.com/Shaharyar-developer/PromptFlow.git#tag=v$pkgver")
sha256sums=('SKIP')  # Will be generated by makepkg -g

build() {
    cd "$pkgname"
    cargo build --release
}

package() {
    cd "$pkgname"
    install -Dm755 "target/release/$pkgname" "$pkgdir/usr/bin/$pkgname"
}

# Optional: run tests
check() {
    cd "$pkgname"
    cargo test
}
